const {test}=require('node:test');
const assert=require('node:assert/strict');
const D=require('../app/src/main/assets/domain.js');
const L=require('../app/src/main/assets/lab-domain.js');
function legacy(patch={}){const p={...D.defaults(),palette:'mineral',accent:'#186B62',background:'#F4F7F6',...patch};delete p.appearance_version;delete p.visual_style;delete p.reduce_transparency;return p;}
test('new workspaces use Glacier and expose independent material preferences',()=>{const p=D.defaults();assert.equal(p.palette,'glacier');assert.equal(p.accent,'#176BDA');assert.equal(p.background,'#F5F8FC');assert.equal(p.visual_style,'glass');assert.equal(p.reduce_transparency,false);assert.equal(p.appearance_version,2);assert.deepEqual(L.palettes.glacier,D.palettes.glacier);assert.deepEqual(Object.keys(L.palettes),Object.keys(D.palettes));});
test('only the complete original Mineral triple migrates and original preference object is unchanged',()=>{const p=legacy({language:'zh',hidden:['notes'],order:['tasks','notes','evidence','learning']}),original=D.clone(p),next=D.normalizePreferences(p);assert.deepEqual(p,original);assert.equal(next.palette,'glacier');assert.equal(next.language,'zh');assert.deepEqual(next.hidden,['notes']);assert.deepEqual(next.order,p.order);assert.deepEqual(D.normalizePreferences(next),next);});
test('custom and explicit alternative palette selections survive appearance migration',()=>{for(const patch of [{palette:'custom'},{palette:'forest',accent:'#147D73',background:'#F6F8F7'},{palette:'mineral',accent:'#186B63'},{palette:'mineral',background:'#F4F7F7'}]){const p=legacy(patch),next=D.normalizePreferences(p);for(const k of ['palette','accent','background'])assert.equal(next[k],p[k]);assert.equal(next.visual_style,'glass');assert.equal(next.appearance_version,2);}});
test('selecting Mineral after the upgrade remains stable after restart',()=>{const p={...D.defaults(),palette:'mineral',accent:'#186B62',background:'#F4F7F6',visual_style:'solid',reduce_transparency:true};const state=D.empty();state.workspace.preferences=p;const restored=D.recover(D.validateState(JSON.parse(JSON.stringify(state))));assert.deepEqual(restored.workspace.preferences,p);});
test('old backup preferences accept missing appearance fields and normalize without modifying records',()=>{const s=D.empty();s.workspace.preferences=legacy();s.lab=L.empty();const e=L.experiment(s.lab,'Saved reactor','Original conditions','S-1',{wall:1,mono:1,boot:'test'});L.record(s.lab,e.id,'Original observation','S-1',{wall:2,mono:2,boot:'test'});const original=JSON.stringify(s.lab);D.validateState(s);D.recover(s);assert.equal(s.workspace.preferences.palette,'glacier');assert.equal(JSON.stringify(s.lab),original);});
test('invalid new preference values are rejected without coercing strings to booleans',()=>{for(const patch of [{visual_style:'blurred-everything'},{reduce_transparency:'false'},{appearance_version:3}]){const s=D.empty();Object.assign(s.workspace.preferences,patch);assert.throws(()=>D.validateState(s));}});
test('backup merge keeps the selected current appearance while round trip preserves added fields',()=>{const current=D.empty(),incoming=D.empty();current.workspace.preferences.visual_style='solid';current.workspace.preferences.reduce_transparency=true;incoming.workspace.preferences=legacy();const result=D.merge(current,incoming);assert.deepEqual(result.state.workspace.preferences,current.workspace.preferences);assert.deepEqual(D.validateState(JSON.parse(JSON.stringify(result.state))).workspace.preferences,current.workspace.preferences);});