const {test}=require('node:test');
const assert=require('node:assert/strict');
const D=require('../app/src/main/assets/domain.js');
const demo=require('../app/src/main/assets/demo-project.json');
function task(date,status='todo',archived=false){return {id:D.uid(),title:'task',planned_date:date,priority:'normal',status,archived};}
test('local calendar date and archived tasks never distort daily/overdue progress',()=>{const w=D.empty().workspace;w.tasks=[task('2026-09-27','done'),task('2026-09-27'),task('2026-09-26'),task('2026-09-26','done'),task('2026-09-26','todo',true)];assert.equal(D.tasksFor(w,'2026-09-27').length,2);assert.equal(D.overdue(w,'2026-09-27').length,1);assert.equal(w.tasks[2].planned_date,'2026-09-26');assert.equal(D.progress([]),null);assert.equal(D.progress([{done:true},{done:false}]),.5);assert.equal(D.day(new Date(2026,8,27,0,5)),'2026-09-27');});
test('workspace round trip preserves language, hidden module data, pinned archive and reopened task',()=>{const s=D.empty();s.workspace.preferences.language='zh';s.workspace.preferences.hidden=['notes'];s.workspace.preferences.order.reverse();s.workspace.notes=[{id:'note',title:'记事',body:'text',archived:true,pinned:true,color:'sand'}];s.workspace.tasks=[task('2026-09-27','doing')];assert.deepEqual(D.validateState(JSON.parse(JSON.stringify(s))),s);s.workspace.preferences.hidden=[];assert.equal(s.workspace.notes[0].body,'text');});
test('rejects malformed dates, unsafe resource URLs and duplicate layout entries',()=>{const s=D.empty();s.workspace.tasks=[task('2026-02-30')];assert.throws(()=>D.validateState(s));s.workspace.tasks=[];s.workspace.goals=[{id:'g',title:'g',archived:false,description:'',resources:['javascript:alert(1)'],steps:[]}];assert.throws(()=>D.validateState(s));s.workspace.goals=[];s.workspace.preferences.order=['tasks','tasks','evidence','learning'];assert.throws(()=>D.validateState(s));});
test('desktop evidence demo is accepted without rewriting original/history',()=>{const p=D.clone(demo),before=JSON.stringify(p);D.validateProject(p);assert.equal(JSON.stringify(p),before);const a=D.merge(D.empty(),p);assert.equal(a.added,1);assert.throws(()=>D.merge(a.state,p),/duplicate/);});
test('backup merge skips existing IDs; does not overwrite edited items or preferences',()=>{const a=D.empty(),b=D.empty();a.workspace.tasks=[{...task('2026-09-27'),id:'same',title:'edited'}];b.workspace.tasks=[{...task('2026-09-27'),id:'same',title:'old'},task('2026-09-28')];b.workspace.preferences.language='zh';const r=D.merge(a,b);assert.equal(r.added,1);assert.equal(r.state.workspace.tasks[0].title,'edited');assert.equal(r.state.workspace.preferences.language,'en');});
test('quote matching belongs to this paper and uses actual page metadata',()=>{const s=demo.studies[0],b=s.documents[0].blocks[0];const src=D.locate(s,[{block_id:b.id,quote:b.text.slice(0,40),matched:false,page:999}])[0];assert.equal(src.matched,true);assert.equal(src.page,b.page);assert.equal(D.locate(s,[{block_id:'another-paper:p1',quote:b.text}])[0].matched,false);assert.equal(D.locate(s,[{block_id:b.id,quote:''}])[0].matched,false);});
test('no invented values for not_found, all selected keys exactly once',()=>{const p=D.clone(demo),s=p.studies[0];const raw={experiments:p.experiments.map(e=>({label:e.label,fields:e.fields.map(f=>D.clone(f.original))}))};assert.equal(D.extract(p,s,raw).length,p.experiments.length);raw.experiments[0].fields[0]={key:p.fields[0].key,value:'invented',unit:null,status:'not_found',sources:[]};assert.throws(()=>D.extract(p,s,raw));raw.experiments[0].fields.pop();assert.throws(()=>D.extract(p,s,raw));});
test('human verification requires local quotes and units; revisions leave originals intact',()=>{const p=D.clone(demo),e=p.experiments[0],f=e.fields.find(f=>f.key==='removal_efficiency');const original=JSON.stringify(f.original);const r={reviewer:'Demo reviewer',note:'Checked condition and units',value:'85',unit:'%',status:'verified',sources:f.sources};D.revise(p,e,f,r);assert.equal(f.revisions.length,1);assert.equal(D.current(f).status,'verified');assert.equal(JSON.stringify(f.original),original);assert.throws(()=>D.revise(p,e,f,{...r,unit:''}),/reviewSource/);assert.throws(()=>D.revise(p,e,f,{...r,sources:[{block_id:'fake',quote:'85%'}]}),/reviewSource/);});
test('interrupted run recovery preserves completed study results',()=>{const s=D.empty();s.projects=[D.clone(demo)];const p=s.projects[0],before=JSON.stringify(p.experiments);p.runs.push({study_id:p.studies[0].id,status:'running'});D.recover(s);assert.equal(p.runs.at(-1).status,'failed');assert.equal(p.runs[0].status,'completed');assert.equal(JSON.stringify(p.experiments),before);});
test('API adapters use structured JSON and reject truncation/refusal',()=>{const p={...D.clone(demo),provider:'openai',model:'user-selected'};const request=D.request(p,p.studies[0]);assert.equal(request.store,false);assert.equal(request.text.format.strict,true);assert.equal(request.text.format.schema.additionalProperties,false);p.provider='anthropic';assert.equal(D.request(p,p.studies[0]).output_config.format.type,'json_schema');assert.throws(()=>D.response('openai',{status:'incomplete'}),/incomplete/);assert.throws(()=>D.response('anthropic',{stop_reason:'max_tokens'}),/incomplete/);assert.throws(()=>D.response('openai',{status:'completed',output:[{type:'message',content:[{type:'refusal'}]}]}),/refused/);assert.deepEqual(D.response('anthropic',{stop_reason:'end_turn',content:[{type:'text',text:'{"experiments":[]}'}]}).raw,{experiments:[]});});
test('input limit fails before any request; CSV protects spreadsheet formulas',()=>{const p=D.clone(demo);p.studies[0].documents[0].blocks[0].text='x'.repeat(160001);assert.throws(()=>D.request(p,p.studies[0]),/tooLong/);p.experiments[0].fields[0].original.value='=1+1';assert.ok(D.csv(p).includes("'=1+1"));assert.ok(D.csv(p).startsWith('\ufeff'));});
test('preset and arbitrary colors choose readable foregrounds',()=>{assert.equal(D.textColor('#ffffff'),'#000000');assert.equal(D.textColor('#000000'),'#FFFFFF');assert.equal(D.textColor('#147D73'),'#FFFFFF');});
