const {test}=require('node:test');
const a=require('node:assert/strict'),L=require('../app/src/main/assets/lab-domain.js');
const clock=(n=0,wall=n,boot='boot1')=>({wall:1700000000000+wall,mono:10000+n,boot});
function fixture(options={}){const l=L.empty(),e=L.experiment(l,'Reactor A','','',clock());const t=L.timer(l,{title:'Oxidation',kind:'staged',experiment_id:e.id,stages:[{title:'Mix',duration_ms:1000},{title:'React',duration_ms:2000}],repeat_count:2,delay_ms:500,transition_mode:'auto',...options},clock());return {l,e,t};}
test('stages advance across delay, boundaries and repeat cycles from one monotonic anchor',()=>{const {l,t}=fixture();L.operate(l,t,'start',clock());let v=L.timerState(t,clock(200));a.equal(v.phase,'delay');a.equal(v.remaining_ms,300);v=L.timerState(t,clock(500));a.equal(v.phase,'stage');a.equal(v.stage_index,0);a.equal(v.remaining_ms,1000);v=L.timerState(t,clock(1600,-100000));a.equal(v.stage_index,1);a.equal(v.remaining_ms,1900);v=L.timerState(t,clock(3600));a.equal(v.repeat_index,1);a.equal(v.stage_index,0);a.equal(v.remaining_ms,900);a.equal(t.anchor.mono,clock().mono);L.validate(l);});
test('pause and resume freeze delay and active stages, reset starts a new generation',()=>{const {l,t}=fixture();L.operate(l,t,'start',clock());L.operate(l,t,'pause',clock(200));a.equal(L.remaining(t,clock(9000)),300);L.operate(l,t,'start',clock(9000));a.equal(L.timerState(t,clock(9300)).phase,'stage');L.operate(l,t,'pause',clock(10200));a.equal(L.elapsed(t,clock(12000)),1400);L.operate(l,t,'reset',clock(12000));a.equal(t.cycle,1);a.equal(t.completed_steps,0);a.equal(t.audit_cursor,0);a.equal(L.timerState(t,clock()).phase,'delay');L.validate(l);});
test('sleep crossing thousands of cycles produces one bounded audit and no duplicate tick audit',()=>{const {l,t}=fixture({repeat_count:100000});L.operate(l,t,'start',clock());const before=l.events.length;L.reconcileTimers(l,clock(100000500));a.equal(l.events.length,before+1);a.equal(l.events.at(-1).boundary_count,66668);a.equal(l.events.at(-1).at.wall,clock(100000500).wall);for(let i=0;i<1000;i++)L.reconcileTimers(l,clock(100000500));a.equal(l.events.length,before+1);L.reconcileTimers(l,clock(500000000));a.equal(t.status,'done');a.equal(t.elapsed_ms,300000500);a.equal(l.events.at(-1).kind,'timer_complete');a.equal(l.events.at(-1).at.wall,clock(300000500).wall);a.equal(l.events.length,before+2);L.validate(l);});
test('manual stage deadline waits indefinitely and confirmation anchors the next stage now',()=>{const {l,t}=fixture({transition_mode:'manual'});L.operate(l,t,'start',clock());L.reconcileTimers(l,clock(10000));a.equal(t.status,'waiting');a.equal(t.elapsed_ms,1500);a.equal(L.timerState(t,clock(100000)).remaining_ms,0);a.equal(t.completed_steps,0);a.equal(l.events.at(-1).at.wall,clock(1500).wall);L.operate(l,t,'confirm',clock(100000));a.equal(t.completed_steps,1);a.equal(t.status,'running');a.equal(L.timerState(t,clock(101000)).remaining_ms,1000);L.reconcileTimers(l,clock(150000));a.equal(t.status,'waiting');a.equal(t.elapsed_ms,3500);L.operate(l,t,'confirm',clock(150000));a.equal(L.timerState(t,clock(150000)).repeat_index,1);for(const n of [151000,153000]){L.reconcileTimers(l,clock(n));L.operate(l,t,'confirm',clock(n));}a.equal(t.status,'done');a.equal(t.elapsed_ms,6500);L.validate(l);});
test('reboot uses wall fallback; importing active stages pauses at correct current stage',()=>{const {l,t}=fixture();L.operate(l,t,'start',clock());a.equal(L.timerState(t,clock(0,4000,'boot2')).repeat_index,1);const imported=L.merge(L.empty(),l,clock(2400)).lab;const copy=imported.timers[0];a.equal(copy.status,'paused');a.equal(copy.elapsed_ms,2400);a.equal(copy.anchor,null);a.equal(L.timerState(copy,clock(9000)).remaining_ms,1100);L.validate(imported);});
test('imported manual deadline cannot silently advance a stage or repeat while paused',()=>{const {l,t}=fixture({transition_mode:'manual'});L.operate(l,t,'start',clock());const out=L.merge(L.empty(),l,clock(100000)).lab,copy=out.timers[0];a.equal(copy.status,'paused');a.equal(copy.elapsed_ms,1500);L.operate(out,copy,'start',clock(150000));L.reconcileTimers(out,clock(150000));a.equal(copy.status,'waiting');a.equal(copy.completed_steps,0);L.validate(out);});
test('finishing or archiving the reactor preserves sample start and actual sampling history',()=>{const {l,e,t}=fixture({transition_mode:'manual'});L.schedule(l,e,[5],clock(60000));const sample=l.timers.find(t=>t.purpose==='sample');L.operate(l,t,'start',clock());L.reconcileTimers(l,clock(2000));L.finishExperiment(l,e,clock(10000));a.equal(t.status,'done');a.equal(t.elapsed_ms,1500);a.equal(l.events.find(e=>e.timer_id===sample.id&&e.kind==='sample_skipped').elapsed_ms,10000);a.equal(l.samples.length,0);a.throws(()=>L.operate(l,t,'confirm',clock(11000)));L.validate(l);});
test('plans reject unsafe or orphan settings without creating timers',()=>{const {l,e}=fixture();for(const options of [{experiment_id:null},{repeat_count:0},{repeat_count:1.5},{delay_ms:-1},{stages:[{title:'x',duration_ms:0}]},{stages:[{title:'',duration_ms:1000}]},{transition_mode:'jump'},{repeat_count:Number.MAX_SAFE_INTEGER}]){const before=l.timers.length;a.throws(()=>L.timer(l,{title:'x',kind:'staged',experiment_id:e.id,stages:[{title:'x',duration_ms:1000}],...options},clock()));a.equal(l.timers.length,before);}});
test('aggregated auto audit separates exact boundary time from later observed active time',()=>{const {l,t}=fixture();L.operate(l,t,'start',clock());L.reconcileTimers(l,clock(1600));const ev=l.events.at(-1);a.equal(ev.kind,'timer_progress');a.equal(ev.at.wall,clock(1500).wall);a.equal(ev.at.mono,clock(1500).mono);a.equal(ev.elapsed_ms,1500);a.equal(ev.timer_elapsed_ms,1500);a.equal(ev.observed_elapsed_ms,1600);a.deepEqual(ev.observed_at,clock(1600));a.equal(ev.boundary_count,2);L.validate(l);});
test('first exact delay or stage boundary has matching event and observed elapsed values',()=>{const {l,t}=fixture();L.operate(l,t,'start',clock());for(const n of [500,1500]){L.reconcileTimers(l,clock(n));const ev=l.events.at(-1);a.equal(ev.timer_elapsed_ms,n);a.equal(ev.observed_elapsed_ms,n);a.equal(ev.elapsed_ms,n);a.deepEqual(ev.at,clock(n));a.deepEqual(ev.observed_at,clock(n));}L.validate(l);});
