[server]
address = "127.0.0.1"
maxUploadSize = 30

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#147D73"
backgroundColor = "#F6F8F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#19312F"
font = "sans serif"

