[server]
address = "127.0.0.1"
maxUploadSize = 30

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#186B62"
backgroundColor = "#F4F7F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#243638"
font = "sans serif"
